services:
  backup_db:
    image: f4b1002/dbk
    build:
      context: .
    container_name: dbk
    env_file:
      - .env
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf
      - ./pg_dumps:/pg_dumps
